version: "3.8"
services:
  backend:
    image: "lolucodes/springboot-react-fullstack:16.8.2022.10.42.56"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev